# Generated by Django 2.0.7 on 2018-11-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
            ],
        ),
    ]
