# Generated by Django 2.0.7 on 2018-11-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
